### ISSUE TITLE
We Need a Logo!

### ISSUE THREAD

**Issue by zefr0x** [zefr0x/hashes#1]
For now, the [assets/io.github.zefr0x.hash_identifier.svg](https://github.com/zefr0x/hash_identifier/blob/main/assets/io.github.zefr0x.hash_identifier.svg) file is empty. It should hold the application's logo, but I'm not a professional logo designer, so I would like to review and accept a professional and high quality logo from the community.

It must match the [GNOME App Icon Guidelines](https://developer.gnome.org/hig/guidelines/app-icons.html) and [FlatHub Quality Guidelines](https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#app-icon).

We should also have an additional symbolic version of it, as the [GNOME App Icon Guidelines](https://developer.gnome.org/hig/guidelines/app-icons.html) says.

The designer's name will be listed in the application's about window in the credits section.

I would like that the logo be under the <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0</a> license, but anyway it's the designer's choice.

Also, if you have some ideas but you are not a designer, you can share them here.

**Comment by bragefuglseth** [comment]
Would you be open to looking into other names as well? "Hash Identifier" is very generic, it would be cool to have something making the app stand out more!

**Comment by zefr0x** [comment]
> Would you be open to looking into other names as well? "Hash Identifier" is very generic, it would be cool to have something making the app stand out more!

I'm open for that. If any one could find a great name it would be great.

But if possible I want to stay away from names that are not translatable.


Also, I want to stay away from names that are derived from languages or cultures that I'm not related to since it would not make any scene for me at least.

**Comment by bragefuglseth** [comment]
If you'd like the name to be translatable, let's keep it as is :+1:

**Comment by bragefuglseth** [comment]
You could potentially shorten it to "Hashes", that's translatable and rolls better off the tongue.

**Comment by zefr0x** [comment]
> You could potentially shorten it to "Hashes", that's translatable and rolls better off the tongue.

Great, I will use it. I will rename it ASAP.

In the feature, it may give the possibility to add a feature for a page with a list of all known hashes within the application as well.

**Comment by bragefuglseth** [comment]
Any thoughts on this?

![Preview](https://github.com/zefr0x/hash_identifier/assets/91388039/c32bc112-0009-40ee-a044-72d9d8dce87b)
